### ISSUE TITLE
Add new detail documentation

### ISSUE THREAD

**Issue by tormozz48** [enb-bem/enb-bem-i18n#20]

**Comment by levonet** [comment]
Андрей, посмотри, пожалуйста
https://github.com/innabelaya/enb-bem-i18n#lang-js-options
документация от @innabelaya, задача ENB-3

**Comment by pavelpower** [comment]
https://ru.bem.info/forum/416/#comment-105822590

**Comment by pavelpower** [comment]
add and this

**Comment by blond** [comment]
Fixed in #68
