### ISSUE TITLE
Try to merge code from github.com/blond/enb-bem-core-i18n

### ISSUE THREAD

**Issue by tormozz48** [enb-bem/enb-bem-i18n#23]
There is new i18n code working with bem-core core.
Some of techs can be merged from it into current package

* [x] Support `i18n` for `bem-core` — #32, #33, #42
* [x] Support `bh` — #31, #46
* [x] Support `bem-xjst` — #34
* [x] Support `xjst` — #47

**Comment by arikon** [comment]
@blond @tormozz48 Зачем?

**Comment by tadatuta** [comment]
@arikon если сойдется, то вместо двух пакетов про сборку локализации будет один с единым API

**Comment by blond** [comment]
@arikon отписал тут https://nda.ya.ru/3Qiss2

**Comment by arikon** [comment]
@tadatuta @blond :+1:
