### ISSUE TITLE
Restore missed functionality for collection of multiple lang keysets in a single file 

### ISSUE THREAD

**Issue by tormozz48** [enb-bem/enb-bem-i18n#42]
"Для старого i18n потеряли возможность собрать несколько языковых кейсетов в одном файле, чтобы потом просто переключать BEM.I18N.lang('current-lang');"

Это критично? Как этого избежать?
Думаю, что этим пользовались. Если это оторвать, то любители считать байты расстроятся от того, что придётся держать в коде ядро несколько раз.

Можно подумать про опцию langs + defaultLang вместо lang. Но не ясно, стоит ли давать такую функциональность для нового i18n.

**Comment by blond** [comment]
Решили пока не делать,
