### ISSUE TITLE
Update `enb-bemxjst` to `2.0.0-beta1`

### ISSUE THREAD

**Issue by blond** [enb-bem/enb-bem-i18n#59]

**Comment by tormozz48** [comment]
Не могу пофиксить ошибку компиляции после обновления зависимости:
```
Error: localAsmts rule failed at: [ 'binop',
  ',',
  [ 'string', 'default' ],
  [ 'json',
    [ 'binding',
      'block',
      [ 'binop', '||', [ 'get', 'vBlock' ], [ 'parens', [Object] ] ] ],
    [ 'binding',
      '_currBlock',
      [ 'condExpr',
        [ 'binop', '||', [Object], [Object] ],
        [ 'get', 'undefined' ],
        [ 'get', 'block' ] ] ],
    [ 'binding', 'elem', [ 'get', 'vElem' ] ],
    [ 'binding',
      'mods',
      [ 'condExpr',
        [ 'get', 'vBlock' ],
        [ 'binop', '||', [Object], [Object] ],
        [ 'getp', [Object], [Object] ] ] ],
    [ 'binding',
      'elemMods',
      [ 'binop', '||', [ 'getp', [Object], [Object] ], [ 'json' ] ] ] ] ]:2
```

Правка самой технологии не дает результата.
Кроме того, обнаружил, что сейчас код `bemhtml` технологии в пакете `enb-bemxjst` плохо приспособлен для его переопределения в пакете `enb-bem-i18n` в отсутствии возможности вызова метода родительской технологии

**Comment by blond** [comment]
Перенёс задачу в `enb-bemjxst-i18n` — https://github.com/enb-bem/enb-bemxjst-i18n/issues/2.

После обновления ошибка не воспроизвелась — https://github.com/enb-bem/enb-bemxjst-i18n/tree/issue-2.
