### ISSUE TITLE
Устаревший пример

### ISSUE THREAD

**Issue by floatdrop** [enb-bem/enb-bem-i18n#83]
__Пример сборки i18n для работы в браузере JavaScript-кода и шаблонов__:

```js
var I18NTech  = require('enb-bem-i18n/techs/i18n'),
    KeysetsTech = require('enb-bem-i18n/techs/keysets'),
// ...
```

Файлов `i18n` и `keysets` больше в пакете нет – на что их заменять в старых конфигах? На `i18n-lang-js` и `i18n-merge-keysets`?

//cc @blond

**Comment by blond** [comment]
А почему нет возможности использовать `1.x`?

> На i18n-lang-js и i18n-merge-keysets?

Да, но не факт, что все примеры заработают как есть для `0.5.x`.

**Comment by floatdrop** [comment]
> А почему нет возможности использовать 1.x?

@blond оказалось, что `1.x` не опубликован на внешнем registry - https://www.npmjs.com/package/enb-bem-i18n

**Comment by blond** [comment]
В `registry` он был, но была проблема с `dist-tags`, исправил. Спасибо!

**Comment by floatdrop** [comment]
@blond :+1:
