### ISSUE TITLE
Свежий релиз

### ISSUE THREAD

**Issue by sullenor** [enb-bem/enb-bem-i18n#86]
Привет,

Хотел поинтересоваться, а можно ли выпустить свежую версию с этим коммитом: https://github.com/enb-bem/enb-bem-i18n/commit/0b1f82646cac7da4386681deac254d1b92eaefb2

Как раз натолкнулся на проблему, что у меня переводы не работают в серверных `priv.js` шаблонах без этой штуки.

Спасибо

**Comment by blond** [comment]
Спасибо, что напомнил.

Выпустил `enb-bem-i18n@1.1.1`.
